name: Android NDK Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Android NDK Executable
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug working directory
      run: |
        echo "Current working directory:"
        echo $GITHUB_WORKSPACE
        ls -R $GITHUB_WORKSPACE

    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r17c
        add-to-path: true

    - name: Compile with ndk-build
      working-directory: jni
      run: |
        ndk-build NDK_APPLICATION_MK=Application.mk APP_BUILD_SCRIPT=Android.mk

    - name: Locate and upload 'su' file
      run: |
        echo "Searching for 'su' file:"
        find $GITHUB_WORKSPACE -name "su" -type f
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: su_binary
        path: libs/x86/su
