name: Android NDK Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Android NDK Executable
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c
        add-to-path: true

    - name: Compile with ndk-build
      run: |
        cd jni  # 进入 jni 目录
        ndk-build NDK_APPLICATION_MK=Application.mk APP_BUILD_SCRIPT=Android.mk

    - name: Debug output directory
      run: |
        ls -R jni/libs  # 检查输出目录结构
        ls -R libs      # 确保正确的输出位置

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: su_binary
        path: jni/libs/x86/su
