name: Android NDK Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Android NDK Executable
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c
        add-to-path: true

    - name: Compile with ndk-build and debug
      run: |
        cd jni
        ndk-build NDK_APPLICATION_MK=Application.mk APP_BUILD_SCRIPT=Android.mk
        echo "Build completed. Debugging output:"
        cd ../..  # 回到 su_project 的上两层目录
        tree -L 3  # 显示三层目录结构

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: su_binary
        path: |
          libs/x86/su
          **/libs/x86/su
